In [1]:
a = 1

위에서 a는 name 또는 identifier, 1은 expression이다.

In [2]:
_b = 2

## PEP8 Style Guide

상수 취급 : 대문자를 사용한다(파이썬에는 상수가 존재하지 않는다 따라서 변수라고 부르지 않는다).
함수 : snakeStyle을 사용한다. myfunction_first
클래스 : camel(python style : myComponent)
python 자체 제공 클래스 : 소문자사용

In [3]:
import keyword

In [4]:
keyword.kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

파이썬을 배우는 것은 키워드와 22가지 스테이트먼트를 사용하는 것을 이야기한다.

In [5]:
type(a)

int

다른 프로그래밍 언어에서는 int8(2^8), unsigned 등등 있지만 파이썬에는 없다.

In [6]:
import numpy as np

In [7]:
x = np.array([129,2,3], dtype='u1')

In [8]:
x

array([129,   2,   3], dtype=uint8)

In [9]:
x+x

array([2, 4, 6], dtype=uint8)

In [10]:
import cv2

In [12]:
cv2.add(x,x)

array([[255],
       [  4],
       [  6]], dtype=uint8)

범위가 넘어가면 돌아오는 연산은 모듈로, 그리고 최대값까지만 가는 연산을 센튜레이티드 연산이라고 한다.

In [13]:
import sys

In [14]:
sys.maxsize

9223372036854775807

파이썬은 위와 같은 수준의 최대 값을 가진다. 그러나 필요한 경우 메모리를 더 할당하여 더 큰 값을 사용할 수 있게 한다. 내부적으로 연산을 하므로 느리다.

파이썬의 숫자형은 4가지가 있다 : int float, bool, None

### Int
정수형 또한 4가지가 있다. 아래와 같다

In [15]:
bin(10)
#따라서 0b30001010 이런것은 안된다.

'0b1010'

In [16]:
oct(10)

'0o12'

In [17]:
hex(10)

'0xa'

In [18]:
#default = 10진법

### Float
머신러닝 딥러닝은 대부분 float32가 기본으로 되어있다.

In [19]:
0.2 + 0.1

0.30000000000000004

In [20]:
0.9 + 0.1

1.0

In [21]:
0.2 + 0.1 == 0.3

False

공식문서 Tutorial 15장에 정확한 값을 구하는 방법이 나와있다. 그러나 정확하게 계산하려 하면 속도가 느려진다. 그러나 float 자체는 연산을 아주 빠르게 한다. 그러나 근사적으로 연산한다. 계산이 빠르므로, 딥러닝, 머신러닝영역에서 많이 사용한다.

In [22]:
1e2 == 100

True

In [23]:
type(1e2)

float

In [24]:
type(100)

int

위에 ==연산을 적용하면 True가 나온다. 내부적으로 같은 값을 표현하냐이다(equality) 이렇게 암시적, 묵시적 변환을 하는 것을 coercion이라고 한다.
타입까지 검사하는 경우 is를 사용한다.

In [25]:
sys.float_info

sys.float_info(max=1.7976931348623157e+308, max_exp=1024, max_10_exp=308, min=2.2250738585072014e-308, min_exp=-1021, min_10_exp=-307, dig=15, mant_dig=53, epsilon=2.220446049250313e-16, radix=2, rounds=1)

In [26]:
a = float('inf')

In [27]:
a

inf

In [28]:
a == a + 1

True

파이썬은 무한대를 float을 사용해서 표현한다.

In [29]:
b = 1.7976931348623157e+309

In [30]:
b

inf

In [31]:
c = 1.7976931348623157e+308

In [32]:
c

1.7976931348623157e+308

In [33]:
float('nan')

nan

즉, 위와 같이 숫자가 아닌 객체도 float으로 표현한다.

### complex(복소수)

In [34]:
c = 1+3j

In [35]:
c * c

(-8+6j)

### boolean

In [36]:
True

True

In [37]:
False

False

In [38]:
type(True)

bool

In [39]:
issubclass(bool, int)

True

In [40]:
str(True)

'True'

In [41]:
True + True

2

In [42]:
2 == True

False

In [43]:
True.__class__.__bases__

(int,)

In [44]:
import numpy as np

In [45]:
np.sctypes

{'int': [numpy.int8, numpy.int16, numpy.int32, numpy.int64],
 'uint': [numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64],
 'float': [numpy.float16, numpy.float32, numpy.float64],
 'complex': [numpy.complex64, numpy.complex128],
 'others': [bool, object, bytes, str, numpy.void]}

In [46]:
100_000_000

100000000

숫자형은 atomic하다. 즉, 쪼갤 수가 없다. 파이썬 3.6부터 사람 관점에서 읽기 편하게 하기 위해 숫자 사이에 언더바를 집어넣을 수 있다.
atomic과 반대되는 개념이 container이다. 하나하나의 원소로 쪼갤 수 있는 요소를 말한다.

## atom <> container
### container를 분류하는 법
- homo / hetero
homo type : 문자열, range, numpy, tensor, array
hetero : 

-sequence / non-sequence

-mutable / immutable

-iterable / non-iterable(보통 sequence 개념에 포함시킬 수 있다)

In [47]:
np.array([1,'1'])

array(['1', '1'], dtype='<U11')

### 문자열

문자는 순서가 달라지면 의미가 달라지는, 순서가 중요한 sequence 데이터 타입이다.

str,<br>
bytes : immutable<br>
bytearray : mutable<br>
(memoryview),

In [48]:
a = '문근영'

In [49]:
a = u'문근영'

파이썬은 기본적으로 유니코드 문자열이다.

In [50]:
b = b'문근영'

SyntaxError: bytes can only contain ASCII literal characters (461317104.py, line 1)

In [51]:
b = b'bytetype'

In [52]:
c = r'\t\rmypage'

In [53]:
print(c)

\t\rmypage


In [54]:
cc = '\t\raaa'

In [55]:
print(cc)

aaa


In [56]:
d = 1
f'{d}'

'1'

In [57]:
a[0]

'문'

In [58]:
a[:2]

'문근'

__getitem__
__len__
위 두가지를 가지고 있으면 sequence 데이터 타입으로 볼 수 있다.

### set

In [59]:
a = {1, 2 ,3}

In [60]:
a[0]

TypeError: 'set' object is not subscriptable

셋은 순서가 없는 집합(nonsequence)으로 인덱싱과 슬라이싱 안된다.

### List, Tuple

In [61]:
c = [1, '2']

In [62]:
c

[1, '2']

In [123]:
c[0]

1

hetero인 sequence container

## Mutable / Immutable
잘 사용하면 편하고, 잘못사용하면 문제가 많음

bytes : immutable<br>
bytearry: mutable

list : mutable<br>
tuple : immutable

set : mutbale<br>
frozenset : immutable

tensor : immutable<br>
numpy : mutable

In [63]:
a = { 1, '1'}
#set : 순서와 중복이 없다.
# 우리가 임의로 순서를 정할 수 없다.

In [64]:
#a = {1,2,1,3,5,1,2,2,3,4,5,1}
a = {1,2,1,3,5,1,2,2,3,4,5,1}

In [65]:
a

{1, 2, 3, 4, 5}

In [66]:
a = 1

In [67]:
a = b = 1

In [68]:
b

1

In [69]:
c = d = [1,2,3]

In [70]:
c[0] = 100

In [71]:
c

[100, 2, 3]

In [72]:
x = 1,2,3

In [73]:
x
#immutable이 기본값이다.

(1, 2, 3)

In [74]:
x, *y = 1,2,3
#y에 들어가는 나머지가 몇개가 될 수 있으므로, 유연하게 mutable을 사용한다.

In [75]:
x

1

In [76]:
y

[2, 3]

In [77]:
*x, y = 1, 2, 3

In [78]:
x

[1, 2]

In [79]:
y

3

In [80]:
a = 1

In [81]:
a += 1

In [149]:
a

2

In [152]:
++a
#++과 같은 연산자가 없다.

2

In [153]:
a++

SyntaxError: invalid syntax (1277751513.py, line 1)

In [82]:
a = [1,2,3]

In [83]:
id(a)

1736389091008

In [84]:
a.append(4) #inplace 테크닉이라고 한다. 그 자리에서 재할당 없이 바로.

In [85]:
id(a)

1736389091008

재할당 또는 rebind없이 값을 변경할 수 있는 경우를 mutable이라고 한다.<br>
이미 선언된 이름의 값을 변경하는 것 = 재할당(메모리 값이 변경됨)
판다스에서 값 변경 후 새로 할당해주어야 하는것은, immutable을 사용하기 때문인데, drop(columns='excol', inplace)할 경우, mutable하게 적용된다.
따라서 mutable은 편리하지만 실수 발생 가능성이 큰데, 이에 따라 텐서플로우에서는 텐서를 immutable로 만들었다.

In [86]:
#뮤터블의 종류
a = [1,2,3]

In [87]:
a.append(4) #return값은 없지만 자신은 변경되는 경우

In [88]:
a

[1, 2, 3, 4]

In [89]:
a.pop() #return값도 있고 자신도 변경되는 경우

4

In [90]:
a

[1, 2, 3]

In [91]:
a.index(1) #return값은 있지만 자신의 값은 변경 안됨

0

MATLAB에는 뮤터블이 없었는데, 이에 숙련되었던 Numpy 제작자는 뮤터블을 잘 썼는데, 다른사람들은 골치아파하기 시작했다. 그래서 텐서플로우에서는 없애버렸다.

### set

set 안에 들어가는 원소들은 Hashable해야한다. 즉 중복을 허용하지 않아야 한다.

In [92]:
a = {[1]}

TypeError: unhashable type: 'list'

리스트는 같은 것으로 변할 수 있으므로, 넣을 수 없다.

In [93]:
a = {(1,[2,3])}

TypeError: unhashable type: 'list'

In [94]:
a = {(1, 2)}

In [95]:
b = {}

In [96]:
type(b)

dict

dictionary의 "키 형태"가 set이다. 

In [97]:
a = {1:2}

In [98]:
a = {[1]:2}

TypeError: unhashable type: 'list'

## Expression - Operator

여러 값을 하나의 평가값으로 만드는 것을 reduce라고 한다. reduce되기 위해서 중간중간에 연산한다.<br>

In [99]:
a = 1 + 1

In [100]:
[1,2,3,] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [101]:
'abc' + 'absd'

'abcabsd'

In [102]:
3 * 'abc'

'abcabcabc'

In [103]:
3 * [1, 3, 4]

[1, 3, 4, 1, 3, 4, 1, 3, 4]

In [109]:
16 // 3 #몫

5

In [105]:
16 % 3

1

In [106]:
16 / 3

5.333333333333333

In [107]:
16 // -3

-6

In [108]:
16 % -3

-2

상용로그에서 정수부와 소수부와 나눴던것 같이, -6 + 0.6666666같이 연산하기 때문에 달라진다.

In [190]:
-16 // 3

-6

In [191]:
-16 % 3

2

In [194]:
%timeit 2*2*2

10.9 ns ± 0.579 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


In [195]:
%timeit 2**3

10.2 ns ± 0.446 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


In [196]:
%timeit 4*4*4

10.6 ns ± 0.32 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


In [197]:
%timeit 4**3

10.5 ns ± 0.535 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


openCV와 같이 처리에 민감한 영역에서는, 하드웨어(GPU, CPU)에서 내부적인 처리가 다르다. 되도록 제곱 쓰지 말고 곱하기 여러번 하라고 할 때가 있다.

In [198]:
x = 1

In [117]:
x.__dir__()

['__new__',
 '__repr__',
 '__hash__',
 '__getattribute__',
 '__lt__',
 '__le__',
 '__eq__',
 '__ne__',
 '__gt__',
 '__ge__',
 '__iter__',
 '__init__',
 '__len__',
 '__getitem__',
 '__setitem__',
 '__delitem__',
 '__add__',
 '__mul__',
 '__rmul__',
 '__contains__',
 '__iadd__',
 '__imul__',
 '__reversed__',
 '__sizeof__',
 'clear',
 'copy',
 'append',
 'insert',
 'extend',
 'pop',
 'remove',
 'index',
 'count',
 'reverse',
 'sort',
 '__class_getitem__',
 '__doc__',
 '__str__',
 '__setattr__',
 '__delattr__',
 '__reduce_ex__',
 '__reduce__',
 '__getstate__',
 '__subclasshook__',
 '__init_subclass__',
 '__format__',
 '__dir__',
 '__class__']

In [118]:
1.__dir__() #.이 있어 float으로 인식해서 문제가 된다.

SyntaxError: invalid decimal literal (651624437.py, line 1)

In [119]:
dir(1)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_count',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 '

#### 비트연산자

In [121]:
a = 3

In [122]:
b = 4

In [123]:
a & b #AND

0

In [124]:
a | b #OR

7

In [125]:
a ^ b #XOR

7

In [126]:
~a

-4

In [127]:
a = {1,2,3}
b = {2,4}

In [128]:
a | b

{1, 2, 3, 4}

In [129]:
a & b

{2}

In [130]:
a ^ b

{1, 3, 4}

In [131]:
x = np.array([1,2,3])

In [132]:
x@x

14

### 비교연산자

In [133]:
a = 100

In [134]:
b = 1e2

In [135]:
a == b #equality 동등

True

In [136]:
a is b #identity 동일

False

In [137]:
'a' < 'A'

False

In [138]:
'a' < 'AA' #시퀀스타입은 합치지 않고, 첫번째부터 순서대로 비교한다.

False

In [139]:
[ 1,2,3,4,5 ] > [100]

False

In [140]:
[ 1,2,3 ] > [1, 0, 100]

True

In [141]:
{1,2,3} < {4,5,6}

False

In [142]:
{1,2,3} > {4,5,6} #순서가 없기 때문에 작다 크다를 비교할 수 없어서 거짓이다.

False

In [143]:
{1,2,3} == {1,2,3}

True

In [144]:
{1,2,3} is {1,2,3}

False

### 조건 연산자

In [145]:
if {''}:
    print('a')
else:
    print('b')

a


파이썬은 true false로 체크하지 않고 존재론적 관점에서 조건문을 체크한다.<br>
int형에서 없는애 : 0<br>
float형에서 없는애 : 0.0<br>
list형에서 없는애 : []<br>
문자열에서 없는애 : ''<br>
dictionary에서 없는애: {}<br>
그냥 없는애 : None

In [146]:
3 and 4 #앞에것이 참이면 뒤에것 반환, 앞에것 거짓이면 앞에것 반환

4

In [147]:
3 or 4 #앞에것이 참이면 앞에것 반환, 앞에것 거짓이면 뒤에것 반환

3

In [148]:
None or 4

4

In [149]:
'' or None

In [150]:
''

''

In [151]:
{} and 3

{}

True False는 1 0과 str빼고는 동일하므로 이것 대신 truthy falsy라는 말을 쓴다.

In [152]:
4 or 3 / 0

4

앞에것이 참이면 뒤를 체크 안한다. 즉, or나 and 쓸 때, 앞에서 평가가 끝난 경우, 뒤에서 문제가 있는데 모르고 있을 수도 있다.

In [153]:
a in [1,2,3] #a가 1또는 2또는 3이냐 - Membership

False

In [154]:
a not in [1,2,3]

True

In [159]:
help('in')

Membership test operations
**************************

The operators "in" and "not in" test for membership.  "x in s"
evaluates to "True" if *x* is a member of *s*, and "False" otherwise.
"x not in s" returns the negation of "x in s".  All built-in sequences
and set types support this as well as dictionary, for which "in" tests
whether the dictionary has a given key. For container types such as
list, tuple, set, frozenset, dict, or collections.deque, the
expression "x in y" is equivalent to "any(x is e or x == e for e in
y)".

For the string and bytes types, "x in y" is "True" if and only if *x*
is a substring of *y*.  An equivalent test is "y.find(x) != -1".
Empty strings are always considered to be a substring of any other
string, so """ in "abc"" will return "True".

For user-defined classes which define the "__contains__()" method, "x
in y" returns "True" if "y.__contains__(x)" returns a true value, and
"False" otherwise.

For user-defined classes which do not define "__contains__(

In [156]:
'a' in [1,2,'3']

False

In [247]:
1 in 'abc'

TypeError: 'in <string>' requires string as left operand, not int

In [248]:
'1' in 'abc'

False

In [249]:
1 in {'a': 1, 'b': 2}

False

In [251]:
for i in {'a': 1, 'b': 2}:
    print(i)

a
b


In [252]:
for i in 1,2,3,4,5:
    print(i)

1
2
3
4
5


### Iterable

__iter__이 정의되어 있으면 iterable이다.

In [254]:
3 in 1 #in 다음에는 무조건 iterable이 와야된다.

TypeError: argument of type 'int' is not iterable

### argument와 parameter의 차이

argument : 인자<br>
parameter : 매개변수

def x(t):  여기서 t는 parameter
    print(t)
    
x(3)   여기서 t는 argument

In [255]:
(1).__iter__()

AttributeError: 'int' object has no attribute '__iter__'

In [256]:
[1,2,3].__iter__()

파이썬에서는 연산자는 편의기능이고 연산자와 관련된 메서드가 실행된다.

In [267]:
class A:
    def __add__(self, x):
        return 1

In [272]:
A()

In [269]:
A + a

TypeError: unsupported operand type(s) for +: 'type' and 'int'